# Generated by Django 4.1.7 on 2023-05-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyurtmaBerish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzildan', models.CharField(max_length=300)),
                ('manzilga', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('raqam', models.CharField(max_length=70)),
            ],
        ),
    ]
