# Generated by Django 4.1.7 on 2023-05-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('raqam', models.CharField(max_length=70)),
                ('xabar', models.TextField(max_length=1000)),
            ],
        ),
    ]
