# Generated by Django 4.1.7 on 2023-05-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyurtmaberish',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='buyurtmaberish',
            old_name='raqam',
            new_name='raqam1',
        ),
    ]
