# Generated by Django 4.1.7 on 2023-05-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_email_buyurtmaberish_email1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='ism',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='raqam',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='xabar',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
