# Generated by Django 4.1.7 on 2023-05-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contactmodel_email_alter_contactmodel_ism_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtmaberish',
            name='email1',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='buyurtmaberish',
            name='manzildan',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='buyurtmaberish',
            name='manzilga',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='buyurtmaberish',
            name='raqam1',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
