# Generated by Django 4.1.7 on 2023-05-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_buyurtmaberish_email1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyurtmaBerishXizmati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzildan', models.CharField(max_length=300)),
                ('manzilga', models.CharField(max_length=300)),
                ('email1', models.EmailField(max_length=254)),
                ('raqam1', models.CharField(max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='BuyurtmaBerish',
        ),
    ]
