# Generated by Django 4.1.7 on 2023-05-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_buyurtmaberishxizmati_delete_buyurtmaberish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtmaberishxizmati',
            name='email1',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='buyurtmaberishxizmati',
            name='manzildan',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='buyurtmaberishxizmati',
            name='manzilga',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='buyurtmaberishxizmati',
            name='raqam1',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
