# Generated by Django 4.1.7 on 2023-05-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_buyurtmaberish_contact_delete_buyurtmaberishxizmati_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtmaberish',
            name='email1',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='buyurtmaberish',
            name='manzildan',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='buyurtmaberish',
            name='manzilga',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='buyurtmaberish',
            name='raqam1',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ism',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='raqam',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='xabar',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
