# Generated by Django 4.1.7 on 2023-05-22 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_choosemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mashina', models.CharField(max_length=100)),
                ('rasm', models.ImageField(upload_to='image/')),
                ('narxi', models.CharField(max_length=50)),
                ('buyurma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.buyurtmaberish')),
                ('tanlash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.choosemodel')),
            ],
        ),
    ]
