# Generated by Django 4.1.7 on 2023-05-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_infomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infomodel',
            name='buyurma',
        ),
    ]
