# Generated by Django 4.1.7 on 2023-05-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_infomodel_delete_infomodell'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyurtmaBerishModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mashina', models.CharField(max_length=50)),
                ('manzildan', models.CharField(max_length=300)),
                ('manzilga', models.CharField(max_length=300)),
                ('email1', models.EmailField(max_length=254)),
                ('raqam1', models.CharField(max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='BuyurtmaBerish',
        ),
    ]
